apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogo-service
  template:
    metadata:
      labels:
        app: catalogo-service
    spec:
      initContainers:
        - name: wait-for-infra
          image: busybox:1.36
          command: ['sh', '-c', 'until nc -z config-server 8888 && nc -z eureka-server 8761 && nc -z postgres-catalogo 5432; do sleep 2; done']
      containers:
        - name: catalogo-service
          image: sideru-platform-catalogo-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-catalogo:5432/catalogo_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "admin"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "admin"
          ports:
            - containerPort: 8082
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 60
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: catalogo-service
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: catalogo-service
