# API Gateway
server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - AddRequestHeader=X-Gateway-Request, true
          routes:
            # TEST: ruta directa sin rewrite
            - id: test-categorias
              uri: lb://catalogo-service
              predicates:
                - Path=/api/categorias
              filters: []
            - id: test-login
              uri: lb://iam-service
              predicates:
                - Path=/api/auth/login
              filters: []
            # IAM (auth + usuarios)
            - id: iam-auth
              uri: lb://iam-service
              predicates:
                - Path=/auth,/auth/**
              filters:
                - RewritePath=/auth(/.*)?, /api/auth$1
            - id: iam-usuarios
              uri: lb://iam-service
              predicates:
                - Path=/usuarios,/usuarios/**
              filters:
                - RewritePath=/usuarios(/.*)?, /api/usuarios$1
            # Catálogo (productos + categorías)
            - id: catalogo-productos
              uri: lb://catalogo-service
              predicates:
                - Path=/productos,/productos/**
              filters:
                - RewritePath=/productos(/.*)?, /api/productos$1
            - id: catalogo-categorias
              uri: lb://catalogo-service
              predicates:
                - Path=/categorias,/categorias/**
              filters:
                - RewritePath=/categorias(/.*)?, /api/categorias$1
            - id: catalogo-admin
              uri: lb://catalogo-service
              predicates:
                - Path=/admin,/admin/**
              filters:
                - RewritePath=/admin(/.*)?, /api/admin$1
            # Pedidos y Cotizaciones
            - id: pedidos-cotizaciones
              uri: lb://pedidos-service
              predicates:
                - Path=/cotizaciones,/cotizaciones/**
              filters:
                - RewritePath=/cotizaciones(/.*)?, /api/cotizaciones$1
            - id: pedidos-pedidos
              uri: lb://pedidos-service
              predicates:
                - Path=/pedidos,/pedidos/**
              filters:
                - RewritePath=/pedidos(/.*)?, /api/pedidos$1
            - id: pedidos-reportes
              uri: lb://pedidos-service
              predicates:
                - Path=/reportes,/reportes/**
              filters:
                - RewritePath=/reportes(/.*)?, /api/reportes$1

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  jwt:
    secret-key: ${JWT_KEY}
